Changes for migration to 5Apr AOSP
Aligning changes required to compile NFC Service
Created soft links to resolve the compilation issue
Resolved this error by defining uses_lib in the Android.bp
error: mismatch in the <uses-library> tags between the build system and the manifest:
	- required libraries in build system: []
	                 vs. in the manifest: [com.nxp.nfc]
	- optional libraries in build system: []
	                 vs. in the manifest: []